### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by itsheng**

### CODE REVIEW

**Comment by miguelzakharia** [comment]
Thank you

**Comment by itsheng** [comment]
@miguelzakharia I have a quick question for you. I tried to integrate this module, but I am seeing a reference to src/aurelia-google-analytics.js reference missing in the console. I am not sure where this reference gets added to the index.html page. Can you please provide some insights? Thanks!

**Comment by miguelzakharia** [comment]
You don't need to add anything to `index.html`. This plugin will automatically inject the GA script when it is initialized. I'm not sure I completely understand the problem you are having. Please provide more detail so I can better help out.

**Comment by itsheng** [comment]
oh... It might be that I didn't use jspm. I used npm but didn't add the reference in Aurelia configuration file?

**Comment by miguelzakharia** [comment]
That sounds like it might cause the problem.

**Pull request merged**
