### PR TITLE
First stab at pageTracking getTitle handler. Resolves #12

### LINKED ISSUE #12: Page Tracking: Option for page title instead of route title
First of all, I LOVE this plugin. It's just what I was looking for, well structured, reasonable, clean. Love it.

__and now the but...__

### Problem
I'm currently using a single route to represent multiple unique pages. Think a blog post. Same route. Different content. Different _titles_. These titles are set using like so 
```
export class BlogPostRoute {
  activate(params, routeConfig, navigationInstruction) {
    //Load blogPost
    routeConfig.navModel.title = blogPost.title;
  }
}
```
Through the "magic" of the aurelia router, that navModel.title ends up as the title of the page. But it doesn't get pulled into aurelia-google-analytics, which makes me sad.

### Proposal
For starters, I will do the work. Second, the gist, I'd like to pass an arg to the the plugin to tell it to grab the title from window.document.title. ```useDocumentTitle``` or something like that.

That's all. 

Simple. Doesn't break existing behavior. But it give me and others who might need this flexibility an option.

But that's just my first stab at it. What do you think? Can I restructure *my* code to avoid this in the first place? Let me know what you think!

### PR DESCRIPTION
**Pull request by ostyn**
So this PR has three parts:

1. Fix some random indentation in package.json
2. Fixed bug where the default clickTracking handler could never be used because of Object.assign() blowing away the default filter method.
3. Put existing pageTracking title-getting behavior into an overridable getTitle() default handler

This would allow me to override getTitle to get the page title instead of the payload.instruction.config.title.

This is my first try at this, so feedback is appreciated. :)
Cheers!

### CODE REVIEW

**Comment by ostyn** [comment]
Up for discussion: is the inclusion of deepmerge worth the extra dependency? It's small(550b gzipped), and it seems nicer to not have that code live in this repo... But what do you folks think?

**Review by miguelzakharia — APPROVED** [review]
This looks good to me. @KevinStong, it seems like this covers your scenario as well. What do you think?

**Comment by KevinStong** [comment]
Hi @miguelzakharia sorry for the delay in getting back with you all and @ostyn thanks for running with this - had a death in the family so been offline for a few days. Havent tested it out yet but yes this looks like it handles my issue as well.  Pulling now and will let you know if I run into any issues thanks!

**Comment by miguelzakharia** [comment]
My condolences, Kevin.

**Comment by ostyn** [comment]
Sorry, Kevin :(

**Comment by KevinStong** [comment]
thanks guys appreciate the condolences,

best,

Kev

**Comment by KevinStong** [comment]
is then being merged in then?

**Comment by miguelzakharia** [comment]
I'll merge it in today and release it. I will not be able to get to it until later this evening though.

**Pull request merged**
